/**
 * 
 */
package wosaic.utilities;

import java.awt.Point;
import java.util.ArrayList;
import java.util.EventObject;

/**
 * @author carl-eriksvensson
 */
public class MosaicEvent extends EventObject {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 2630812124983782513L;

	/**
	 * A list of coordinates that were updated
	 */
	public ArrayList<Point> Coords;

	/**
	 * The new pixel for each coordinate
	 */
	public Pixel UpdatedPixel;

	/**
	 * Creates an event that specifies what part of the mosaic was just updated.
	 * 
	 * @param src the object that generated this event
	 * @param coords A list of coordinates that were updated
	 * @param pixel The pixel object that was added to the mosaic
	 */
	public MosaicEvent(final Object src, final ArrayList<Point> coords,
			final Pixel pixel) {
		super(src);
		Coords = coords;
		UpdatedPixel = pixel;
	}

	/**
	 * String representation of the event
	 * 
	 * @see java.util.EventObject#toString()
	 */
	@Override
	public String toString() {
		// FIXME: Write a more reasonable "toString"
		return "MosaicUpdated";
	}

}
