package wosaic;

import javax.swing.JFrame;

/**
 * The Application version of the Wosaic project
 * 
 * @author scott
 */
public class WosaicApplication extends javax.swing.JFrame {

	/**
	 * Version ID generated by Eclipse
	 */
	private static final long serialVersionUID = 5823811339873852749L;

	public static void main(final String[] args) {
		new WosaicApplication();
	}

	public WosaicApplication() {
		super("Wosaic");
		initialize();
	}

	/**
	 * Initialize the class.
	 */
	private void initialize() {

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		add(new WosaicUI());

		// Allow WosaicUI to determine preferred size
		pack();

		setVisible(true);
	}
}
