//
//  ImagePreview.java
//  
//
//  Borrowed from Sun tutorial:
//	http://java.sun.com/docs/books/tutorial/uiswing/components/filechooser.html

package wosaic.utilities;

import javax.swing.*;
import java.beans.*;
import java.awt.*;
import java.io.File;

/**
 * An accessory that can be added to a JFileChooser to
 * display a small preview of the selected image.
 * 
 * Based on ImagePreview.java by FileChooserDemo2.java. 
 * */
public class ImagePreview extends JComponent
                          implements PropertyChangeListener {
    /**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -1118759912160048880L;
	ImageIcon thumbnail = null;
    File file = null;

    /**
     * Default constructor
     * 
     * @param fc the filechooser we will associate with
     */
    public ImagePreview(JFileChooser fc) {
        setPreferredSize(new Dimension(100, 50));
        fc.addPropertyChangeListener(this);
    }

    /**
     * Create an ImageIcon for the currently selected image, if applicable
     */
    public void loadImage() {
        if (file == null) {
            thumbnail = null;
            return;
        }

        //Don't use createImageIcon (which is a wrapper for getResource)
        //because the image we're trying to load is probably not one
        //of this program's own resources.
        ImageIcon tmpIcon = new ImageIcon(file.getPath());
        if (tmpIcon.getIconWidth() > 90) {
            thumbnail = new ImageIcon(tmpIcon.getImage().
                                      getScaledInstance(90, -1,
                                                  Image.SCALE_DEFAULT));
        } else { //no need to miniaturize
            thumbnail = tmpIcon;
        }
    }

    public void propertyChange(PropertyChangeEvent e) {
        boolean update = false;
        String prop = e.getPropertyName();

        //If the directory changed, don't show an image.
        if (JFileChooser.DIRECTORY_CHANGED_PROPERTY.equals(prop)) {
            file = null;
            update = true;

        //If a file became selected, find out which one.
        } else if (JFileChooser.SELECTED_FILE_CHANGED_PROPERTY.equals(prop)) {
            file = (File) e.getNewValue();
            update = true;
        }

        //Update the preview accordingly.
        if (update) {
            thumbnail = null;
            if (isShowing()) {
                loadImage();
                repaint();
            }
        }
    }

    /**
     * Paint our preview icon to the screen
     * @see javax.swing.JComponent#paintComponent(java.awt.Graphics)
     */
    @Override
	protected void paintComponent(Graphics g) {
        if (thumbnail == null) {
            loadImage();
        }
        if (thumbnail != null) {
            int x = getWidth()/2 - thumbnail.getIconWidth()/2;
            int y = getHeight()/2 - thumbnail.getIconHeight()/2;

            if (y < 0) {
                y = 0;
            }

            if (x < 5) {
                x = 5;
            }
            thumbnail.paintIcon(this, g, x, y);
        }
    }
}
