/**
 * 
 */
package wosaic.utilities;

import java.awt.Point;
import java.util.ArrayList;
import java.util.EventObject;

/**
 * @author carl-eriksvensson
 * 
 */
public class MosaicEvent extends EventObject {

    /**
         * Generated by Eclipse
         */
    private static final long serialVersionUID = 2630812124983782513L;

    public ArrayList<Point> Coords;

    /**
         * Creates an event that specifies what part of the mosaic was just
         * updated.
         * 
         * @param src
         *                the object that generated this event
         * @param coords
         *                A list of coordinates that were updated
         */
    public MosaicEvent(final Object src, final ArrayList<Point> coords) {
	super(src);
	Coords = coords;
    }

    // FIXME: Write a more reasonable "toString"
    @Override
    public String toString() {
	return "MosaicUpdated";
    }

}
